////////////////////////////Module's Description////////////////////////////////
/*!
 * \file       CM_Q03_codes.h
 * \brief      This is the CM_Q03 codes driver made by S4IoT
 * \details    *For more information, please refer to the included documentation
 *             provided.
 * \version    1.0.0
 * \author     S4IoT
 * \copyright  (c) 2018, Mobile IoT Latam S.A.P.I. de CV. All rights reserved.
 */
/////////////////////////End of Module Description//////////////////////////////

////////////////////////////////Include Guard///////////////////////////////////

#ifndef CM_Q03_CODES_H_
#define CM_Q03_CODES_H_

///////////////////////////End of Includes Area/////////////////////////////////

//////////////////////////Definitions Area//////////////////////////////////////
/** System codes offset*/
#define SYS_CODES 		1000
/** General codes offset*/
#define GENERAL_CODES 	2000
/** TCP/IP codes offset*/
#define TCP_IP_CODES 	3000
/** MQTT codes offset*/
#define MQTT_CODES 		4000
/** GNSS codes offset*/
#define GNSS_CODES 		5000
/** FTP codes offset*/
#define FTP_CODES		6000
/** FILE codes offset*/
#define FILE_CODES      7000
/** FILE codes offset*/
#define HTTPS_CODES     8000
//////////////////////////End of Definitions Area///////////////////////////////

//////////////////////////Structures and Enumerators////////////////////////////
/*!
 	 \brief Enumerator to define the possible errors returned by
 	 	 	 the shield.
 */
/** TODO: Comment each of the enumerator values.*/
typedef enum{
	Success,
	No_connection_to_phone = 1,
	Phoneadaptor_link_reserved,
	Operation_no_allowed_CME,
	Operation_no_supported_CME,
	PH_SIM_PIN_required,
	PH_FSIM_PIN_required,
	PH_FSIM_PUK_required,
	Phone_failure,
	SIM_not_inserted_CME = 10,
	SIM_PIN_required,
	SIM_PUK_required_CME,
	SIM_failure_CME,
	SIM_busy_CME,
	SIM_wrong_CME,
	Incorrect_password,
	SIM_PIN2_required_CME,
	SIM_PUK2_required_CME,
	Memory_full_CME = 20,
	Invalid_index,
	Not_found,
	Memory_failure_CME,
	TextString_too_long,
	Invalid_char_in_TextString,
	DialString_too_long,
	Invalid_char_in_DualString,
	No_network_service = 30,
	Network_timeout_CME,
	Network_not_allowed,
	Network_PIN_required = 40,
	Network_PUK_required,
	Network_subset_PIN_required,
	Network_subset_PUK_required,
	Service_provider_PIN_required,
	Service_provider_PUK_required,
	Corporate_PIN_required,
	Corporate_PUK_required,
	ME_failure = 300,
	SMS_ME_reserved,
	Operation_no_allowed_CMS,
	Operation_no_supported_CMS,
	Invalid_PDU_mode,
	Invalid_text_mode,
	SIM_not_inserted_CMS = 310,
	SIM_pin_necessary,
	PH_SIM_pin_necessary,
	SIM_failure_CMS,
	SIM_busy_CMS,
	SIM_wrong_CMS,
	SIM_PUK_required_CMS,
	SIM_PIN2_required_CMS,
	SIM_PUK2_required_CMS,
	Memory_failure_CMS = 320,
	Invalid_memory_index,
	Memory_full_CMS,
	SMSC_address_unknow = 330,
	No_network,
	Network_timeout_CMS,
	Unknow = 500,
	SIM_not_ready = 512,
	Message_length_exceeds,
	Invalid_request_parameters,
	ME_storage_failure,
	Invalid_service_mode = 517,
	More_message_to_send_state_error =  528,
	MO_SMS_is_not_allow,
	GPRS_is_suspended,
	ME_storage_full,
	Unknown_error = 550,
	Operation_blocked,
	Invalid_parameter,
	Memory_not_enough,
	Create_socket_failed,
	Operation_not_supported,
	Socket_bind_failed,
	Socket_listen_failed,
	Socket_write_failed,
	Socket_read_failed,
	Socket_accept_failed,
	Open_PDP_context_failed,
	Close_PDP_context_failed,
	Socket_identity_has_been_used,
	DNS_busy,
	DNS_parse_failed,
	Socket_connection_failed,
	Socket_has_been_closed,
	Operation_busy,
	Operation_timeout,
	PDP_context_break_down,
	Cancel_send,
	Operation_not_allowed,
	APN_not_configured,
	Port_busy,
	Operation_succesful,
	ERROR = SYS_CODES,
	Timeout,
	User_Error,
	Not_registered_in_Network,
	CM_Q03_is_ready,
	CM_Q03_not_ready,

	Not_Searching = GENERAL_CODES,
	Registered,
	Searching,
	Registration_Denied,
	Unknown,
	Registered_Roaming,
	SIM_READY,
	SIM_PIN,
 	SIM_PUK,
	SIM_PIN2,
	SIM_PUK2,
	PH_SP_PIN,
	PH_SP_PUK,
	PH_NET_PIN,
	PH_NET_PUK,
	PH_CORP_PIN,
	PH_CORP_PUK,
	PH_NETSUB_PIN,
	PH_NETSUB_PUK,
	No_Operator_Selected,
	
	TCP_IP_Service_opened_successfully = TCP_IP_CODES,
	TCP_IP_PDP_Deactivated,
	TCP_IP_PDP_Activated,
	TCP_IP_No_data_to_read,
	TCP_IP_Socket_Initial,
	TCP_IP_Socket_Opening,
	TCP_IP_Socket_Connected,
	TCP_IP_Socket_Listening,
	TCP_IP_Socket_Closing,
	TCP_IP_Send_Fail,
	TCP_IP_Unknown_error = 550 + TCP_IP_CODES,
	TCP_IP_Operation_blocked,
	TCP_IP_Invalid_parameters,
	TCP_IP_Memory_not_enough,
	TCP_IP_Create_socket_failed,
	TCP_IP_Operation_not_supported,
	TCP_IP_Socket_bind_failed,
	TCP_IP_Socket_listen_failed,
	TCP_IP_Socket_write_failed,
	TCP_IP_Socket_read_failed,
	TCP_IP_Socket_accept_failed,
	TCP_IP_Open_PDP_context_failed,
	TCP_IP_Close_PDP_context_failed,
	TCP_IP_Socket_identify_has_been_used,
	TCP_IP_DNS_busy,
	TCP_IP_DNS_parse_failed,
	TCP_IP_Socket_connect_failed,
	TCP_IP_Socket_has_been_closed,
	TCP_IP_Operation_busy,
	TCP_IP_Operation_timeout,
	TCP_IP_PDP_context_broken_down,
	TCP_IP_Cancel_Send,
	TCP_IP_Operation_not_allowed,
	TCP_IP_APN_not_configured,
	TCP_IP_Port_busy,
	TCP_IP_Invalid_Connect_ID,
	TCP_IP_Invalid_Context_ID,


	MQTT_Network_Opened_Successfully = MQTT_CODES,
	MQTT_Wrong_parameter,
	MQTT_Identifier_Occupied,
	MQTT_Failed_Active_PDP,
	MQTT_Failed_Parse_Domain_Name,
	MQTT_Network_Disconnection_Error,
	MQTT_Failed_Open_Network,
	MQTT_Packet_sent_successfully,
	MQTT_Packet_retransmission,
	MQTT_Failed_send_packet,
	MQTT_notConnected,
	MQTT_initial,
	MQTT_connecting,
	MQTT_connected,
	MQTT_disconnecting,
	MQTT_Connection_Accepted,
	MQTT_Connection_Refused_Unacceptable_Protocol_Version,
	MQTT_Connection_Refused_Identifier_Rejected,
	MQTT_Connection_Refused_Server_Unavialable,
	MQTT_Connection_Refused_Bad_UserName_or_Password,
	MQTT_Connection_Refused_Not_Authorized,
	MQTT_No_message_received,
	MQTT_Failed_to_close_connection,
	MQTT_Connection_closed_succesfully,
	MQTT_Failed_to_close_network,
	MQTT_Network_closed_succesfully,
	MQTT_Invalid_Connect_ID,
	MQTT_Connection_Closed_Or_Reset_By_Peer,
	MQTT_PINGREQ_Packet_Failed,
	MQTT_CONNECT_Packet_Failed,
	MQTT_CONNACK_Packet_Failed,
	MQTT_DISCONNECT_Packet_Sent,
	MQTT_Disconected_Due_To_Multiple_Failed_Sendings,
	MQTT_Link_Or_Server_Unavailable,

	GNSS_Invalid_parameter = 501 + GNSS_CODES,
	GNSS_Operation_not_supported,
	GNSS_subsystem_busy,
	GNSS_Session_ir_ongoing,
	GNSS_Session_not_active,
	GNSS_Operation_timeout,
	GNSS_Function_not_enabled,
	GNSS_Time_information_error,
	GNSS_XTRA_not_enabled,
	GNSS_Validity_time_out_of_range = 512 + GNSS_CODES,
	GNSS_Internal_resource_error,
	GNSS_locked,
	GNSS_End_by_E911,
	GNSS_Not_fixed_now,
	GNSS_GeoFence_ID_not_existed,
	GNSS_Unknown_error = 549 + GNSS_CODES,

	FTP_Opening_Server = FTP_CODES,
	FTP_Server_open_and_idle,
	FTP_Transferring_data_with_server,
	FTP_Closing_server,
	FTP_Server_is_close,
	FTP_Unknown_error = 601 + FTP_CODES,
	FTP_server_blocked,
	FTP_server_busy,
	FTP_DNS_parse_failed,
	FTP_Network_error,
	FTP_Control_connection_closed,
	FTP_Data_connection_closed,
	FTP_Socket_closed_by_peer,
	FTP_Timeout_error,
	FTP_Invalid_parameter,
	FTP_Failed_to_open_file,
	FTP_File_position_invalid,
	FTP_File_error,
	FTP_Service_not_available_closing_control_connection,
	FTP_Open_data_connection_failed,
	FTP_Connection_closed_transfer_aborted,
	FTP_Requested_file_action_not_taken,
	FTP_Requested_action_aborted_local_error_in_processing,
	FTP_Requested_action_not_taken_insufficient_system_storage,
	FTP_Syntax_error_command_unrecognized,
	FTP_Syntax_error_in_parameters_or_arguments,
	FTP_Command_not_implemented,
	FTP_Bad_sequence_of_commands,
	FTP_Command_parameter_not_implemented,
	FTP_not_logged_in,
	FTP_Need_account_for_storing_file,
	FTP_Requested_action_not_taken,
	FTP_Requested_action_aborted_page_type_unknown,
	FTP_Requested_file_action_aborted,
	FTP_Requested_file_name_invalid,
	FTP_SSL_authentication_failed,

    File_Invalid_input_value=400+FILE_CODES,
    File_Larger_than_the_size_of_the_file,
    File_Read_zero_byte,
    File_Drive_full,
    File_File_not_found=405+FILE_CODES,
    File_Invalid_file_name,
    File_File_already_existed,
    File_Fail_to_write_the_file=409+FILE_CODES,
    File_Fail_to_open_the_file,
    File_Fail_to_read_the_file,
    File_Reach_the_max_number_of_file_allowed_to_be_opened=413+FILE_CODES,
    File_The_file_read_only,
    File_Invalid_file_descriptor=416+FILE_CODES,
    File_Fail_to_list_the_file,
    File_Fail_to_delete_the_file,
    File_Fail_to_get_disk_info,
    File_No_space,
    File_Time_out,
    File_File_too_large=423+FILE_CODES,
    File_Invalid_parameter=425+FILE_CODES,
    File_File_already_opened,

	HTTPS_OK = 200 + HTTPS_CODES,
	HTTPS_Forbidden = 403 + HTTPS_CODES,
	HTTPS_Not_Found,
	HTTPS_Conflict = 409 + HTTPS_CODES,
	HTTPS_Length_Required = 411 + HTTPS_CODES,
	HTTPS_Internal_Server_Error = 500 + HTTPS_CODES,
	HTTPS_Unknown_error = 701 + HTTPS_CODES,
    HTTPS_Timeout,
	HTTPS_Busy,
	HTTPS_UART_busy,
	HTTPS_No_GET_POST_requests,
	HTTPS_Network_Busy,
	HTTPS_Network_Open_Failed,
	HTTPS_Network_No_Configuration,
	HTTPS_Network_Deactived,
	HTTPS_Network_Error,
	HTTPS_URL_Error,
	HTTPS_Empty_URL,
	HTTPS_IP_Address_Error,
	HTTPS_DNS_error,
	HTTPS_Socket_Create_error,
	HTTPS_Socket_Connect_error,
	HTTPS_Socket_Write_Error,
	HTTPS_Socket_Read_Error,
	HTTPS_Socket_Closed,
	HTTPS_Data_Encode_Error,
	HTTPS_Data_Decode_Error,
	HTTPS_Read_Timeout,
	HTTPS_Response_Failed,
	HTTPS_Incomming_Call_Busy,
	HTTPS_Voice_Call_Busy,
	HTTPS_Input_Timeout,
	HTTPS_Wait_Data_Timeout,
	HTTPS_Wait_Response_Timeout,
	HTTPS_Memory_Allocation_Failed,
	HTTPS_Invalid_Parameter
}cm_q03_codes_t;
//////////////////////End of Structures and Enumerators/////////////////////////

#endif /* CM_Q03_CODES_H_ */
/////////////////////////End of Include Guard Closing///////////////////////////
